
package webservice.metier.difficulty;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DifficultyManagerService", targetNamespace = "http://difficulty.metier.webService/", wsdlLocation = "http://localhost:8686/DifficultyManager/?wsdl")
public class DifficultyManagerService
    extends Service
{

    private final static URL DIFFICULTYMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException DIFFICULTYMANAGERSERVICE_EXCEPTION;
    private final static QName DIFFICULTYMANAGERSERVICE_QNAME = new QName("http://difficulty.metier.webService/", "DifficultyManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8686/DifficultyManager/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DIFFICULTYMANAGERSERVICE_WSDL_LOCATION = url;
        DIFFICULTYMANAGERSERVICE_EXCEPTION = e;
    }

    public DifficultyManagerService() {
        super(__getWsdlLocation(), DIFFICULTYMANAGERSERVICE_QNAME);
    }

    public DifficultyManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DIFFICULTYMANAGERSERVICE_QNAME, features);
    }

    public DifficultyManagerService(URL wsdlLocation) {
        super(wsdlLocation, DIFFICULTYMANAGERSERVICE_QNAME);
    }

    public DifficultyManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DIFFICULTYMANAGERSERVICE_QNAME, features);
    }

    public DifficultyManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DifficultyManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DifficultyManagerWS
     */
    @WebEndpoint(name = "DifficultyManagerWSPort")
    public DifficultyManagerWS getDifficultyManagerWSPort() {
        return super.getPort(new QName("http://difficulty.metier.webService/", "DifficultyManagerWSPort"), DifficultyManagerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DifficultyManagerWS
     */
    @WebEndpoint(name = "DifficultyManagerWSPort")
    public DifficultyManagerWS getDifficultyManagerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://difficulty.metier.webService/", "DifficultyManagerWSPort"), DifficultyManagerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DIFFICULTYMANAGERSERVICE_EXCEPTION!= null) {
            throw DIFFICULTYMANAGERSERVICE_EXCEPTION;
        }
        return DIFFICULTYMANAGERSERVICE_WSDL_LOCATION;
    }

}
