
package webservice.metier.difficulty;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DifficultyManagerWS", targetNamespace = "http://difficulty.metier.webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DifficultyManagerWS {


    /**
     * 
     * @return
     *     returns java.util.List<webservice.metier.difficulty.Difficulty>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDifficulties", targetNamespace = "http://difficulty.metier.webService/", className = "webservice.metier.difficulty.GetDifficulties")
    @ResponseWrapper(localName = "getDifficultiesResponse", targetNamespace = "http://difficulty.metier.webService/", className = "webservice.metier.difficulty.GetDifficultiesResponse")
    @Action(input = "http://difficulty.metier.webService/DifficultyManagerWS/getDifficultiesRequest", output = "http://difficulty.metier.webService/DifficultyManagerWS/getDifficultiesResponse")
    public List<Difficulty> getDifficulties();

}
