
package webservice.metier.ustensil;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UstensilManagerService", targetNamespace = "http://ustensil.metier.webService/", wsdlLocation = "http://localhost:8686/UstensilManager/?wsdl")
public class UstensilManagerService
    extends Service
{

    private final static URL USTENSILMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException USTENSILMANAGERSERVICE_EXCEPTION;
    private final static QName USTENSILMANAGERSERVICE_QNAME = new QName("http://ustensil.metier.webService/", "UstensilManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8686/UstensilManager/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USTENSILMANAGERSERVICE_WSDL_LOCATION = url;
        USTENSILMANAGERSERVICE_EXCEPTION = e;
    }

    public UstensilManagerService() {
        super(__getWsdlLocation(), USTENSILMANAGERSERVICE_QNAME);
    }

    public UstensilManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USTENSILMANAGERSERVICE_QNAME, features);
    }

    public UstensilManagerService(URL wsdlLocation) {
        super(wsdlLocation, USTENSILMANAGERSERVICE_QNAME);
    }

    public UstensilManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USTENSILMANAGERSERVICE_QNAME, features);
    }

    public UstensilManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UstensilManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UstensilManagerWS
     */
    @WebEndpoint(name = "UstensilManagerWSPort")
    public UstensilManagerWS getUstensilManagerWSPort() {
        return super.getPort(new QName("http://ustensil.metier.webService/", "UstensilManagerWSPort"), UstensilManagerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UstensilManagerWS
     */
    @WebEndpoint(name = "UstensilManagerWSPort")
    public UstensilManagerWS getUstensilManagerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ustensil.metier.webService/", "UstensilManagerWSPort"), UstensilManagerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USTENSILMANAGERSERVICE_EXCEPTION!= null) {
            throw USTENSILMANAGERSERVICE_EXCEPTION;
        }
        return USTENSILMANAGERSERVICE_WSDL_LOCATION;
    }

}
