
package webservice.metier.ustensil;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UstensilManagerWS", targetNamespace = "http://ustensil.metier.webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UstensilManagerWS {


    /**
     * 
     * @param quantity
     * @param ustensil
     * @param recipeId
     */
    @WebMethod
    @RequestWrapper(localName = "addUstensil", targetNamespace = "http://ustensil.metier.webService/", className = "webservice.metier.ustensil.AddUstensil")
    @ResponseWrapper(localName = "addUstensilResponse", targetNamespace = "http://ustensil.metier.webService/", className = "webservice.metier.ustensil.AddUstensilResponse")
    @Action(input = "http://ustensil.metier.webService/UstensilManagerWS/addUstensilRequest", output = "http://ustensil.metier.webService/UstensilManagerWS/addUstensilResponse")
    public void addUstensil(
        @WebParam(name = "ustensil", targetNamespace = "")
        Ustensil ustensil,
        @WebParam(name = "quantity", targetNamespace = "")
        int quantity,
        @WebParam(name = "recipeId", targetNamespace = "")
        int recipeId);

    /**
     * 
     * @return
     *     returns java.util.List<webservice.metier.ustensil.Ustensil>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUstensils", targetNamespace = "http://ustensil.metier.webService/", className = "webservice.metier.ustensil.GetUstensils")
    @ResponseWrapper(localName = "getUstensilsResponse", targetNamespace = "http://ustensil.metier.webService/", className = "webservice.metier.ustensil.GetUstensilsResponse")
    @Action(input = "http://ustensil.metier.webService/UstensilManagerWS/getUstensilsRequest", output = "http://ustensil.metier.webService/UstensilManagerWS/getUstensilsResponse")
    public List<Ustensil> getUstensils();

}
