
package webservice.metier.tag;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TagManagerService", targetNamespace = "http://tag.metier.webService/", wsdlLocation = "http://localhost:8686/TagManager/?wsdl")
public class TagManagerService
    extends Service
{

    private final static URL TAGMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TAGMANAGERSERVICE_EXCEPTION;
    private final static QName TAGMANAGERSERVICE_QNAME = new QName("http://tag.metier.webService/", "TagManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8686/TagManager/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TAGMANAGERSERVICE_WSDL_LOCATION = url;
        TAGMANAGERSERVICE_EXCEPTION = e;
    }

    public TagManagerService() {
        super(__getWsdlLocation(), TAGMANAGERSERVICE_QNAME);
    }

    public TagManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TAGMANAGERSERVICE_QNAME, features);
    }

    public TagManagerService(URL wsdlLocation) {
        super(wsdlLocation, TAGMANAGERSERVICE_QNAME);
    }

    public TagManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TAGMANAGERSERVICE_QNAME, features);
    }

    public TagManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TagManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TagManagerWS
     */
    @WebEndpoint(name = "TagManagerWSPort")
    public TagManagerWS getTagManagerWSPort() {
        return super.getPort(new QName("http://tag.metier.webService/", "TagManagerWSPort"), TagManagerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TagManagerWS
     */
    @WebEndpoint(name = "TagManagerWSPort")
    public TagManagerWS getTagManagerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tag.metier.webService/", "TagManagerWSPort"), TagManagerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TAGMANAGERSERVICE_EXCEPTION!= null) {
            throw TAGMANAGERSERVICE_EXCEPTION;
        }
        return TAGMANAGERSERVICE_WSDL_LOCATION;
    }

}
