
package webservice.metier.tag;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TagManagerWS", targetNamespace = "http://tag.metier.webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TagManagerWS {


    /**
     * 
     * @return
     *     returns java.util.List<webservice.metier.tag.Tag>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTags", targetNamespace = "http://tag.metier.webService/", className = "webservice.metier.tag.GetTags")
    @ResponseWrapper(localName = "getTagsResponse", targetNamespace = "http://tag.metier.webService/", className = "webservice.metier.tag.GetTagsResponse")
    @Action(input = "http://tag.metier.webService/TagManagerWS/getTagsRequest", output = "http://tag.metier.webService/TagManagerWS/getTagsResponse")
    public List<Tag> getTags();

    /**
     * 
     * @param tag
     * @param recipeId
     */
    @WebMethod
    @RequestWrapper(localName = "addTag", targetNamespace = "http://tag.metier.webService/", className = "webservice.metier.tag.AddTag")
    @ResponseWrapper(localName = "addTagResponse", targetNamespace = "http://tag.metier.webService/", className = "webservice.metier.tag.AddTagResponse")
    @Action(input = "http://tag.metier.webService/TagManagerWS/addTagRequest", output = "http://tag.metier.webService/TagManagerWS/addTagResponse")
    public void addTag(
        @WebParam(name = "tag", targetNamespace = "")
        Tag tag,
        @WebParam(name = "recipeId", targetNamespace = "")
        int recipeId);

}
