
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SecuriteService", targetNamespace = "http://webService/", wsdlLocation = "http://localhost:8686/Securite/?wsdl")
public class SecuriteService
    extends Service
{

    private final static URL SECURITESERVICE_WSDL_LOCATION;
    private final static WebServiceException SECURITESERVICE_EXCEPTION;
    private final static QName SECURITESERVICE_QNAME = new QName("http://webService/", "SecuriteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8686/Securite/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECURITESERVICE_WSDL_LOCATION = url;
        SECURITESERVICE_EXCEPTION = e;
    }

    public SecuriteService() {
        super(__getWsdlLocation(), SECURITESERVICE_QNAME);
    }

    public SecuriteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECURITESERVICE_QNAME, features);
    }

    public SecuriteService(URL wsdlLocation) {
        super(wsdlLocation, SECURITESERVICE_QNAME);
    }

    public SecuriteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECURITESERVICE_QNAME, features);
    }

    public SecuriteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecuriteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SecuriteWS
     */
    @WebEndpoint(name = "SecuriteWSPort")
    public SecuriteWS getSecuriteWSPort() {
        return super.getPort(new QName("http://webService/", "SecuriteWSPort"), SecuriteWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecuriteWS
     */
    @WebEndpoint(name = "SecuriteWSPort")
    public SecuriteWS getSecuriteWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "SecuriteWSPort"), SecuriteWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECURITESERVICE_EXCEPTION!= null) {
            throw SECURITESERVICE_EXCEPTION;
        }
        return SECURITESERVICE_WSDL_LOCATION;
    }

}
