
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SecuriteWS", targetNamespace = "http://webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecuriteWS {


    /**
     * 
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encrypt", targetNamespace = "http://webService/", className = "webservice.Encrypt")
    @ResponseWrapper(localName = "encryptResponse", targetNamespace = "http://webService/", className = "webservice.EncryptResponse")
    @Action(input = "http://webService/SecuriteWS/encryptRequest", output = "http://webService/SecuriteWS/encryptResponse")
    public String encrypt(
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param email
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mailIsValid", targetNamespace = "http://webService/", className = "webservice.MailIsValid")
    @ResponseWrapper(localName = "mailIsValidResponse", targetNamespace = "http://webService/", className = "webservice.MailIsValidResponse")
    @Action(input = "http://webService/SecuriteWS/mailIsValidRequest", output = "http://webService/SecuriteWS/mailIsValidResponse")
    public boolean mailIsValid(
        @WebParam(name = "email", targetNamespace = "")
        String email);

}
