
package webservice.metier.recipe;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RecipeManagerWS", targetNamespace = "http://recipe.metier.webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecipeManagerWS {


    /**
     * 
     * @param maxDifficulty
     * @param recipeType
     * @param maxCookingTime
     * @return
     *     returns java.util.List<webservice.metier.recipe.Recipe>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecipes", targetNamespace = "http://recipe.metier.webService/", className = "webservice.metier.recipe.GetRecipes")
    @ResponseWrapper(localName = "getRecipesResponse", targetNamespace = "http://recipe.metier.webService/", className = "webservice.metier.recipe.GetRecipesResponse")
    @Action(input = "http://recipe.metier.webService/RecipeManagerWS/getRecipesRequest", output = "http://recipe.metier.webService/RecipeManagerWS/getRecipesResponse")
    public List<Recipe> getRecipes(
        @WebParam(name = "maxDifficulty", targetNamespace = "")
        int maxDifficulty,
        @WebParam(name = "recipeType", targetNamespace = "")
        int recipeType,
        @WebParam(name = "maxCookingTime", targetNamespace = "")
        int maxCookingTime);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastRecipeId", targetNamespace = "http://recipe.metier.webService/", className = "webservice.metier.recipe.GetLastRecipeId")
    @ResponseWrapper(localName = "getLastRecipeIdResponse", targetNamespace = "http://recipe.metier.webService/", className = "webservice.metier.recipe.GetLastRecipeIdResponse")
    @Action(input = "http://recipe.metier.webService/RecipeManagerWS/getLastRecipeIdRequest", output = "http://recipe.metier.webService/RecipeManagerWS/getLastRecipeIdResponse")
    public int getLastRecipeId();

    /**
     * 
     * @param recipe
     */
    @WebMethod
    @RequestWrapper(localName = "addRecipe", targetNamespace = "http://recipe.metier.webService/", className = "webservice.metier.recipe.AddRecipe")
    @ResponseWrapper(localName = "addRecipeResponse", targetNamespace = "http://recipe.metier.webService/", className = "webservice.metier.recipe.AddRecipeResponse")
    @Action(input = "http://recipe.metier.webService/RecipeManagerWS/addRecipeRequest", output = "http://recipe.metier.webService/RecipeManagerWS/addRecipeResponse")
    public void addRecipe(
        @WebParam(name = "recipe", targetNamespace = "")
        Recipe recipe);

}
