
package webservice.metier.recipetype;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecipeTypeManagerService", targetNamespace = "http://recipeType.metier.webService/", wsdlLocation = "http://localhost:8686/RecipeTypeManager/?wsdl")
public class RecipeTypeManagerService
    extends Service
{

    private final static URL RECIPETYPEMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECIPETYPEMANAGERSERVICE_EXCEPTION;
    private final static QName RECIPETYPEMANAGERSERVICE_QNAME = new QName("http://recipeType.metier.webService/", "RecipeTypeManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8686/RecipeTypeManager/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECIPETYPEMANAGERSERVICE_WSDL_LOCATION = url;
        RECIPETYPEMANAGERSERVICE_EXCEPTION = e;
    }

    public RecipeTypeManagerService() {
        super(__getWsdlLocation(), RECIPETYPEMANAGERSERVICE_QNAME);
    }

    public RecipeTypeManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECIPETYPEMANAGERSERVICE_QNAME, features);
    }

    public RecipeTypeManagerService(URL wsdlLocation) {
        super(wsdlLocation, RECIPETYPEMANAGERSERVICE_QNAME);
    }

    public RecipeTypeManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECIPETYPEMANAGERSERVICE_QNAME, features);
    }

    public RecipeTypeManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecipeTypeManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecipeTypeManagerWS
     */
    @WebEndpoint(name = "RecipeTypeManagerWSPort")
    public RecipeTypeManagerWS getRecipeTypeManagerWSPort() {
        return super.getPort(new QName("http://recipeType.metier.webService/", "RecipeTypeManagerWSPort"), RecipeTypeManagerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecipeTypeManagerWS
     */
    @WebEndpoint(name = "RecipeTypeManagerWSPort")
    public RecipeTypeManagerWS getRecipeTypeManagerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://recipeType.metier.webService/", "RecipeTypeManagerWSPort"), RecipeTypeManagerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECIPETYPEMANAGERSERVICE_EXCEPTION!= null) {
            throw RECIPETYPEMANAGERSERVICE_EXCEPTION;
        }
        return RECIPETYPEMANAGERSERVICE_WSDL_LOCATION;
    }

}
