
package webservice.metier.recipetype;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RecipeTypeManagerWS", targetNamespace = "http://recipeType.metier.webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecipeTypeManagerWS {


    /**
     * 
     * @return
     *     returns java.util.List<webservice.metier.recipetype.RecipeType>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecipeTypes", targetNamespace = "http://recipeType.metier.webService/", className = "webservice.metier.recipetype.GetRecipeTypes")
    @ResponseWrapper(localName = "getRecipeTypesResponse", targetNamespace = "http://recipeType.metier.webService/", className = "webservice.metier.recipetype.GetRecipeTypesResponse")
    @Action(input = "http://recipeType.metier.webService/RecipeTypeManagerWS/getRecipeTypesRequest", output = "http://recipeType.metier.webService/RecipeTypeManagerWS/getRecipeTypesResponse")
    public List<RecipeType> getRecipeTypes();

}
