
package webservice.metier.ingredient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IngredientManagerService", targetNamespace = "http://ingredient.metier.webService/", wsdlLocation = "http://localhost:8686/IngredientManager/?wsdl")
public class IngredientManagerService
    extends Service
{

    private final static URL INGREDIENTMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException INGREDIENTMANAGERSERVICE_EXCEPTION;
    private final static QName INGREDIENTMANAGERSERVICE_QNAME = new QName("http://ingredient.metier.webService/", "IngredientManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8686/IngredientManager/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INGREDIENTMANAGERSERVICE_WSDL_LOCATION = url;
        INGREDIENTMANAGERSERVICE_EXCEPTION = e;
    }

    public IngredientManagerService() {
        super(__getWsdlLocation(), INGREDIENTMANAGERSERVICE_QNAME);
    }

    public IngredientManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INGREDIENTMANAGERSERVICE_QNAME, features);
    }

    public IngredientManagerService(URL wsdlLocation) {
        super(wsdlLocation, INGREDIENTMANAGERSERVICE_QNAME);
    }

    public IngredientManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INGREDIENTMANAGERSERVICE_QNAME, features);
    }

    public IngredientManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IngredientManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IngredientManagerWS
     */
    @WebEndpoint(name = "IngredientManagerWSPort")
    public IngredientManagerWS getIngredientManagerWSPort() {
        return super.getPort(new QName("http://ingredient.metier.webService/", "IngredientManagerWSPort"), IngredientManagerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IngredientManagerWS
     */
    @WebEndpoint(name = "IngredientManagerWSPort")
    public IngredientManagerWS getIngredientManagerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ingredient.metier.webService/", "IngredientManagerWSPort"), IngredientManagerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INGREDIENTMANAGERSERVICE_EXCEPTION!= null) {
            throw INGREDIENTMANAGERSERVICE_EXCEPTION;
        }
        return INGREDIENTMANAGERSERVICE_WSDL_LOCATION;
    }

}
