
package webservice.metier.ingredient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IngredientManagerWS", targetNamespace = "http://ingredient.metier.webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IngredientManagerWS {


    /**
     * 
     * @return
     *     returns java.util.List<webservice.metier.ingredient.Ingredient>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIngredients", targetNamespace = "http://ingredient.metier.webService/", className = "webservice.metier.ingredient.GetIngredients")
    @ResponseWrapper(localName = "getIngredientsResponse", targetNamespace = "http://ingredient.metier.webService/", className = "webservice.metier.ingredient.GetIngredientsResponse")
    @Action(input = "http://ingredient.metier.webService/IngredientManagerWS/getIngredientsRequest", output = "http://ingredient.metier.webService/IngredientManagerWS/getIngredientsResponse")
    public List<Ingredient> getIngredients();

    /**
     * 
     * @param ingredient
     * @param quantity
     * @param recipeId
     */
    @WebMethod
    @RequestWrapper(localName = "addIngredient", targetNamespace = "http://ingredient.metier.webService/", className = "webservice.metier.ingredient.AddIngredient")
    @ResponseWrapper(localName = "addIngredientResponse", targetNamespace = "http://ingredient.metier.webService/", className = "webservice.metier.ingredient.AddIngredientResponse")
    @Action(input = "http://ingredient.metier.webService/IngredientManagerWS/addIngredientRequest", output = "http://ingredient.metier.webService/IngredientManagerWS/addIngredientResponse")
    public void addIngredient(
        @WebParam(name = "ingredient", targetNamespace = "")
        Ingredient ingredient,
        @WebParam(name = "quantity", targetNamespace = "")
        int quantity,
        @WebParam(name = "recipeId", targetNamespace = "")
        int recipeId);

}
