
package webservice.metier.step;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StepManagerService", targetNamespace = "http://step.metier.webService/", wsdlLocation = "http://localhost:8686/StepManager/?wsdl")
public class StepManagerService
    extends Service
{

    private final static URL STEPMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException STEPMANAGERSERVICE_EXCEPTION;
    private final static QName STEPMANAGERSERVICE_QNAME = new QName("http://step.metier.webService/", "StepManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8686/StepManager/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STEPMANAGERSERVICE_WSDL_LOCATION = url;
        STEPMANAGERSERVICE_EXCEPTION = e;
    }

    public StepManagerService() {
        super(__getWsdlLocation(), STEPMANAGERSERVICE_QNAME);
    }

    public StepManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STEPMANAGERSERVICE_QNAME, features);
    }

    public StepManagerService(URL wsdlLocation) {
        super(wsdlLocation, STEPMANAGERSERVICE_QNAME);
    }

    public StepManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STEPMANAGERSERVICE_QNAME, features);
    }

    public StepManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StepManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StepManagerWS
     */
    @WebEndpoint(name = "StepManagerWSPort")
    public StepManagerWS getStepManagerWSPort() {
        return super.getPort(new QName("http://step.metier.webService/", "StepManagerWSPort"), StepManagerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StepManagerWS
     */
    @WebEndpoint(name = "StepManagerWSPort")
    public StepManagerWS getStepManagerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://step.metier.webService/", "StepManagerWSPort"), StepManagerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STEPMANAGERSERVICE_EXCEPTION!= null) {
            throw STEPMANAGERSERVICE_EXCEPTION;
        }
        return STEPMANAGERSERVICE_WSDL_LOCATION;
    }

}
