
package webservice.metier.step;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StepManagerWS", targetNamespace = "http://step.metier.webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StepManagerWS {


    /**
     * 
     * @param step
     * @param recipeId
     * @param order
     */
    @WebMethod
    @RequestWrapper(localName = "addStep", targetNamespace = "http://step.metier.webService/", className = "webservice.metier.step.AddStep")
    @ResponseWrapper(localName = "addStepResponse", targetNamespace = "http://step.metier.webService/", className = "webservice.metier.step.AddStepResponse")
    @Action(input = "http://step.metier.webService/StepManagerWS/addStepRequest", output = "http://step.metier.webService/StepManagerWS/addStepResponse")
    public void addStep(
        @WebParam(name = "step", targetNamespace = "")
        Step step,
        @WebParam(name = "order", targetNamespace = "")
        int order,
        @WebParam(name = "recipeId", targetNamespace = "")
        int recipeId);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastStepId", targetNamespace = "http://step.metier.webService/", className = "webservice.metier.step.GetLastStepId")
    @ResponseWrapper(localName = "getLastStepIdResponse", targetNamespace = "http://step.metier.webService/", className = "webservice.metier.step.GetLastStepIdResponse")
    @Action(input = "http://step.metier.webService/StepManagerWS/getLastStepIdRequest", output = "http://step.metier.webService/StepManagerWS/getLastStepIdResponse")
    public int getLastStepId();

}
